name: Prod CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/prod/Jusicool-Ai
            cd /home/ubuntu/prod/Jusicool-Ai

            if [ ! -d ".git" ]; then
              git clone -b main https://github.com/Jusicool-Ver-2-0/Jusicool-Ai .
            else
              git fetch origin main
              git reset --hard origin/main
            fi


            docker stop jusicool-ai || true
            docker rm jusicool-ai || true
            docker build -t jusicool-ai .
            docker run -d --name jusicool-ai -p 3000:3000 jusicool-ai
